apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: production # matchLabels should match with the Labels inside the pod template
  replicas: 10
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
      - name: nginx-2
        image: nginx
